### PR TITLE
Health and Rotation

### PR DESCRIPTION
**Pull request by Demuxx**
Added functionality to check if a connector is healthy along with tests for it.  Added a fault_tolerance attribute to distributor to be decided by the consumer. Also added functionality to rotate the connectors round-robbin style.

### CODE REVIEW

**Comment by mkb** [comment]
Good stuff. Can you rebase your branch against master? The merge was proving tricky.

**Comment by Demuxx** [comment]
Not sure what I'm doing wrong here. I rebased my branch with origin/master, but it's still saying cannot be automatically merged. :-\

**Comment by mkb** [comment]
One potential pitfall is if you don't fetch or pull before rebasing then you won't actually be getting the latest code. 

The steps I usually follow are something like:
1. Check in what I've got on my branch
2. `git fetch` to see whether there has been any activity on master
3. `git rebase origin/master`
4. Make sure tests still pass
5. `git push -f origin <mybranch>`
6. Make sure my branch still passes CI
7. `git checkout master`
8. Hope no sneaky fuckers pushed to master after my last fetch. 
9. `git pull`
10. `git merge <mybranch>`
11. `git push origin master`
12. Push rejected? Curse sneaky fuckers and rebase again. 

In general, the more often you rebase, the easier it will be. Less than once per day spells certain doom. During active development with a non-pairing partner, I will rebase obsessively. 

Let me know if that helps.

**Comment by mkb** [comment]
Interesting. Looking at the diffs I see a bunch of whitespace changes. I can't tell from the GH web UI what they are. Given the volume I am guessing linebreaks but I'll have to check when I'm at a real computer. No doubt there is a simple configuration fix to make all that go away.

**Comment by mkb** [comment]
Confirmed. Looks like a linebreak problem. Check your gitconfig and your editor config. Here's my .gitconfig:  https://gist.github.com/mkb/79b67daf835971a23e96

**Comment by mkb** [comment]
Looks like adding --whitespace=fix to the rebase command will fix the immediate problem. Setting editor config and git config to unix-style line breaks will keep it from coming up again. Found this article on doing the git config part. Turns out I didn't have that set up either. https://help.github.com/articles/dealing-with-line-endings

**Pull request merged**
